apiVersion: v1
kind: Pod
metadata:
  name: approot
  labels:
    app: approot
spec:
  hostname: approot
  containers:
    - name: {{ .Chart.Name }}
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      imagePullPolicy: Always
      ports:
        - containerPort: 8085
