apiVersion: v1
kind: Service
metadata:
  name: {{ include "approot.fullname" . }}
  labels:
    {{- include "approot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8085
      protocol: TCP
  selector:
    {{- include "approot.selectorLabels" . | nindent 4 }}
